#!/usr/bin/env node
// Minimal static file server for /aide/, the local mirror of the docs+guides
// help content (generated by scripts/generate-aide.mjs). Serves the aide/
// directory under the /aide/ URL prefix, matching the absolute paths baked
// into the generated pages.

import { createServer } from 'node:http'
import { readFile, stat } from 'node:fs/promises'
import { join, extname, normalize } from 'node:path'
import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const aideDir = join(root, 'aide')
const port = process.env.PORT || 3033

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.eot': 'application/vnd.ms-fontobject',
  '.ttf': 'font/ttf',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.avif': 'image/avif',
}

createServer(async (req, res) => {
  const url = new URL(req.url, 'http://localhost')
  if (!url.pathname.startsWith('/aide/')) {
    res.writeHead(404).end('Not found')
    return
  }
  const relative = normalize(url.pathname.slice('/aide/'.length)).replace(/^(\.\.[/\\])+/, '')
  const candidates = [join(aideDir, relative), join(aideDir, `${relative}.html`)]
  for (const filePath of candidates) {
    try {
      const s = await stat(filePath)
      if (!s.isFile()) continue
      const body = await readFile(filePath)
      res.writeHead(200, { 'Content-Type': MIME[extname(filePath)] || 'application/octet-stream' })
      res.end(body)
      return
    } catch {
      // try next candidate
    }
  }
  res.writeHead(404).end('Not found')
}).listen(port, () => {
  console.log(`Serving aide/ on http://localhost:${port}/aide/`)
})
